[wokwi]
version = 1
elf = "../.pio/build/esp32/firmware.elf"
firmware = "../.pio/build/esp32/firmware.bin"
gdbServerPort = 3333
rfc2217ServerPort = 4001
[[net.forward]]
from = "localhost:23"
to = "target:23"
